_format_version: "3.0"
_transform: true

services:
  - name: graphql-service
    url: http://graphql-service:4000
    protocol: http
    routes:
      - name: graphql-route
        paths:
          - /graphql
        strip_path: false

  - name: notification-service
    url: http://notification-service:8080
    protocol: http
    routes:
      - name: notification-route
        paths:
          - /notifications
        strip_path: false


plugins:
  - name: rate-limiting
    service: graphql-service
    config:
      minute: 5
      policy: local

  - name: cors
    service: graphql-service
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - OPTIONS
      headers:
        - Accept
        - Authorization
        - Content-Type
        - Origin
        - X-Requested-With